name: CI Build
on:
  workflow_call:
    secrets:
      VAULT_TOKEN:
        required: true
jobs:
  NodeJSBuild:
    runs-on: self-hosted
    steps:
      - name: Use the secrets
        run: |
          echo "API Token available"
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
